Add Volunteer create feature
SuperMan4eg/NewPetHome pull request #9
Opened 2024-08-19 13:35 UTC by SuperMan4eg

2024-08-19 17:53 UTC, YADARAN1 requested changes

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.API/Controllers/VolunteersController.cs
> +
Почему нет проверки на неудачную обработку?

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Applications/Volunteers/IVolunteersRepository.cs
> +    Task<Volunteer> GetById(VolunteerId volunteerId);
Where CancellationToken?

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Domain/Volunteers/PetDetails.cs
> +    protected PetDetails()
можно поменять на private

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Domain/Volunteers/Requisite.cs
> +    public static Requisite Create(string name, string description)
Закончи валидацию

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Domain/Volunteers/Volunteer.cs
> +    public int CountPetsFindHome()
метод можно в 1 строку написать

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Domain/Volunteers/Volunteer.cs
> +    public int CountPetsLookingHome()
Этот тоже

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Domain/Volunteers/Volunteer.cs
> +    public int CountPetsInTreatment()
И тут

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Domain/Volunteers/Volunteer.cs
> +        FullName = fullName;
Из FullName лучше сделать value object

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Domain/Volunteers/Volunteer.cs
> +        Details = VolunteerDetails.Create(requisites, socialNetworks);
Почему у тебя в доменной модели создание реквизитов и соц.сетей? Переделать

2024-08-19 17:53 UTC, YADARAN1 commented on NewPetHome.Backend/Src/NewPetHome.Infrastructure/Repositories/VolunteersRepository.cs
> +    public async Task<Volunteer> GetById(VolunteerId volunteerId)
CancellationToken забыл

2024-08-20 11:24 UTC, YaraOduvanchik requested changes
Исправил не всё

2024-08-20 11:42 UTC, YaraOduvanchik approved these changes

2024-08-20 12:13 UTC, merged